## DEV
version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum install -y docker
    runtime-versions:
      java: corretto17
  pre_build: ## 빌드 전
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      ## ECR Login
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 392434356039.dkr.ecr.ap-northeast-1.amazonaws.com
  build: ## 빌드
    commands:
      - echo Build started on `date`
      - pwd
      - cd ./simple_project ## 프로젝트 루트 디렉토리로 진입
      - echo simple project root directory
      - mvn clean package ## maven 빌드
  post_build:
    commands:
      - echo Build completed on `date`
      - echo docker start!
      - service docker start
      - echo ls!
      - ls
      ## ECR Push 명령 참조
      - echo push this image!
      - docker build -t my_spring_dev .
      - docker tag my_spring_dev:latest 392434356039.dkr.ecr.ap-northeast-1.amazonaws.com/my_spring_dev:latest
      - docker images
      - docker push 392434356039.dkr.ecr.ap-northeast-1.amazonaws.com/my_spring_dev:latest
artifacts:
  files:
    - simple_project/target/simple_project-0.0.1-SNAPSHOT.jar