version: 0.2

phases:
  install:
    runtime-versions: ## 런타임 설정
      java: corretto8 ## Java 1.8을 사용하였으나 corretto11은 Java11 을 기반으로 한 상위 버전이므로 사용 가능
  pre_build: ## 빌드 전
    commands:
      - echo Nothing to do in the pre_build phase...
  build: ## 빌드
    commands:
      - echo Build started on `date`
      - mvn clean install ## maven 빌드
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar ## 아티팩트 출력 경로